update wb_shortcuts, put wb_shortcuts initial switch completion into bash completion

diff --git a/src/CommandLine/wb_shortcuts b/src/CommandLine/wb_shortcuts
--- a/src/CommandLine/wb_shortcuts
+++ b/src/CommandLine/wb_shortcuts
@@ -111,7 +111,7 @@ function create_function ()
     global_descrip+=("$*")
 }
 
-function switch_to_func_name
+function switch_to_func_name ()
 {
     printf '%s' "$1" | sed 's/^-//' | sed 's/-/_/g'
 }
@@ -254,6 +254,77 @@ function cifti_demean ()
     #let the exit hook clean up the normed temporaries, we're done
 }
 
+create_function "-cifti-dlabel-split-cortex" "SEPARATE SURFACE LABELS INTO LEFT/RIGHT"
+function cifti_dlabel_split_cortex ()
+{
+    local function_switch="$1"
+    shift
+    if (($# < 1))
+    then
+        echo "`switch_to_descrip $function_switch`"
+        echo "   $global_script_name $function_switch"
+        echo "      <dlabel-in> - input dlabel file"
+        echo "      <dlabel-out> - output - output dlabel file"
+        echo
+        #wrap guide for 80 columns                                                           |
+        echo "      For every label represented on left or right cortex, rename it with a"
+        echo "      prefix of 'L_' or 'R_', and change the label values as needed to keep"
+        echo "      the new names separate."
+        echo
+        return 0
+    fi
+    if (($# != 2))
+    then
+        error "function requires 2 arguments, $# provided"
+    fi
+    #to prevent it from also changing label keys in a multi-map dlabel (because gifti doesn't support label tables per-map),
+    #we need to loop through the columns
+    local i num_maps=`wb_command -file-information -only-number-of-maps "$1"`
+    local -a mergeargs
+    for ((i = 1; i <= num_maps; ++i))
+    do
+        add_temporary_files "$2".temp$i.dlabel.nii "$2".temp$i.L.label.gii "$2".temp$i.R.label.gii "$2".temp$i.nii.gz
+        add_temporary_files "$2".temp$i.L.txt "$2".temp$i.R.txt "$2".temp$i.vol.txt
+        wb_command -cifti-merge "$2".temp$i.dlabel.nii -cifti "$1" -column $i
+        wb_command -cifti-separate "$2".temp$i.dlabel.nii COLUMN -label CORTEX_LEFT "$2".temp$i.L.label.gii -label CORTEX_RIGHT "$2".temp$i.R.label.gii -volume-all "$2".temp$i.nii.gz -crop
+        #these are temporary files and will be deleted regardless, go ahead and overwrite them
+        #LEFT
+        wb_command -gifti-label-add-prefix "$2".temp$i.L.label.gii L_ "$2".temp$i.L.label.gii
+        #need to remove the unused ones from the table so we don't get stupid overlaps
+        wb_command -label-export-table "$2".temp$i.L.label.gii "$2".temp$i.L.txt
+        #mute the warning from loading a label as a metric
+        wb_command -metric-label-import "$2".temp$i.L.label.gii \
+                                        "$2".temp$i.L.txt \
+                                        "$2".temp$i.L.label.gii \
+                                        -drop-unused-labels 2> /dev/null
+        
+        #RIGHT
+        wb_command -gifti-label-add-prefix "$2".temp$i.R.label.gii R_ "$2".temp$i.R.label.gii
+        #need to remove the unused ones from the table so we don't get stupid overlaps
+        wb_command -label-export-table "$2".temp$i.R.label.gii "$2".temp$i.R.txt
+        #mute the warning from loading a label as a metric
+        wb_command -metric-label-import "$2".temp$i.R.label.gii \
+                                        "$2".temp$i.R.txt \
+                                        "$2".temp$i.R.label.gii \
+                                        -drop-unused-labels 2> /dev/null
+        #VOLUME
+        #need to also remove unused labels from this, too
+        wb_command -volume-label-export-table "$2".temp$i.nii.gz 1 "$2".temp$i.vol.txt
+        #no warning to mute
+        wb_command -volume-label-import "$2".temp$i.nii.gz \
+                                        "$2".temp$i.vol.txt \
+                                        "$2".temp$i.nii.gz \
+                                        -drop-unused-labels
+        
+        wb_command -cifti-create-dense-from-template "$2".temp$i.dlabel.nii "$2".temp$i.dlabel.nii -label CORTEX_LEFT "$2".temp$i.L.label.gii -label CORTEX_RIGHT "$2".temp$i.R.label.gii -volume-all "$2".temp$i.nii.gz -from-cropped
+        rm -f "$2".temp$i.L.label.gii "$2".temp$i.R.label.gii "$2".temp$i.nii.gz
+        rm -f "$2".temp$i.L.txt "$2".temp$i.R.txt "$2".temp$i.vol.txt
+        mergeargs+=(-cifti "$2".temp$i.dlabel.nii)
+    done
+    wb_command -cifti-merge "$2" "${mergeargs[@]}"
+    #let the cleanup function remove the intermediate cifti files
+}
+
 create_function "-command-help-search" "SEARCH WB_COMMAND HELP"
 function command_help_search ()
 {
@@ -263,6 +334,7 @@ function command_help_search ()
     then
         echo "`switch_to_descrip $function_switch`"
         echo "   $global_script_name $function_switch"
+        echo "      [-also-deprecated] - also search deprecated commands"
         echo "      <search-string> - grep pattern to search for"
         echo
         #wrap guide for 80 columns                                                           |
@@ -272,6 +344,25 @@ function command_help_search ()
     fi
     local -a switches
     readarray -t switches < <(wb_command -list-commands | awk '{print $1}')
+    if [[ "$1" == "-also-deprecated" ]]
+    then
+        shift
+        local -a depswitches
+        readarray -t depswitches < <(wb_command -list-deprecated-commands | awk '{print $1}')
+        switches+=("${depswitches[@]}")
+    fi
+    #we could add a -- option to denote end of options, but then it would be harder to search for -- rather than for an option
+    if (($# < 1))
+    then
+        error "function requires an argument"
+    fi
+    #requiring quotes when searching for a phrase is slightly inconvenient
+    #on the other hand, a phrase could get split across lines, so that is error prone anyway
+    #if (($# != 1))
+    #then
+    #    warning "more than one argument provided, check for unquoted spaces and spelling of options"
+    #fi
+    local i
     for ((i = 0; i < ${#switches[@]}; ++i))
     do
         #use $* in case someone didn't quote, but keep it all in the pattern argument
@@ -314,9 +405,9 @@ function freesurfer_resample_prep ()
         echo
         return 0
     fi
-    if (($# < 7))
+    if (($# != 7))
     then
-        error "function requires 7 arguments"
+        error "function requires 7 arguments, $# provided"
     fi
     if [[ "$7" != *.surf.gii ]]
     then
@@ -359,9 +450,9 @@ function import_probtrack_roi ()
         echo
         return 0
     fi
-    if (($# < 3))
+    if (($# != 3))
     then
-        error "function requires 3 arguments"
+        error "function requires 3 arguments, $# provided"
     fi
     #make temporaries based on the output file name
     add_temporary_files "$3.temp1-$$" "$3.temp2-$$"
@@ -409,6 +500,7 @@ function label_concatenate ()
         error "function requires 2 or more arguments"
     fi
     local -a merge_arg_array
+    local i
     for ((i = 2; i <= $#; ++i))
     do
         merge_arg_array+=("-label" "${!i}" "${maparg[@]}")
@@ -453,6 +545,7 @@ function metric_concatenate ()
         error "function requires 2 or more arguments"
     fi
     local -a merge_arg_array
+    local i
     for ((i = 2; i <= $#; ++i))
     do
         merge_arg_array+=("-metric" "${!i}" "${maparg[@]}")
@@ -483,6 +576,7 @@ function scene_file_concatenate ()
         error "function requires 2 or more arguments"
     fi
     local -a merge_arg_array
+    local i
     for ((i = 2; i <= $#; ++i))
     do
         merge_arg_array+=("-scene-file" "${!i}")
@@ -527,6 +621,7 @@ function volume_concatenate ()
         error "function requires 2 or more arguments"
     fi
     local -a merge_arg_array
+    local i
     for ((i = 2; i <= $#; ++i))
     do
         merge_arg_array+=("-volume" "${!i}" "${maparg[@]}")
@@ -538,6 +633,7 @@ function volume_concatenate ()
 function do_operation ()
 {
     #use the existence of a short description to denote existence of the function
+    local i
     for ((i = 0; i < ${#global_switch[@]}; ++i))
     do
         if [[ "${global_switch[$i]}" == "$1" ]]
@@ -574,6 +670,7 @@ function do_operation ()
 function switch_to_descrip ()
 {
     #because we aren't using associative arrays, because mac's ancient bash
+    local i
     for ((i = 0; i < ${#global_switch[@]}; ++i))
     do
         if [[ "${global_switch[$i]}" == "$1" ]]
@@ -587,7 +684,7 @@ function switch_to_descrip ()
 
 function list_functions ()
 {
-    local maxlength=0
+    local i maxlength=0
     for ((i = 0; i < ${#global_switch[@]}; ++i))
     do
         local thislength=`printf '%s' "${global_switch[$i]}" | wc -c`
@@ -605,6 +702,7 @@ function list_functions ()
 function all_functions_help ()
 {
     #assume that the commands all print their help info when given no additional arguments besides the command switch itself
+    local i
     for ((i = 0; i < ${#global_switch[@]}; ++i))
     do
         `switch_to_func_name "${global_switch[$i]}"` "${global_switch[$i]}"
@@ -622,8 +720,16 @@ function error ()
     exit 1
 }
 
+function warning ()
+{
+    echo >&2
+    echo "Warning: $*" >&2
+    echo >&2
+}
+
 function check_functions ()
 {
+    local i
     for ((i = 0; i < ${#global_switch[@]}; ++i))
     do
         local function_name=`switch_to_func_name "${global_switch[$i]}"`
